cat = {
  "suburban" : "railway station",
  "administrative area" : "city center",
  "adventure vehicle" : "trail system",
  "advertising/marketing" : "company",
  "afghan" : "restaurant",
  "african" : "restaurant",
  "agricultural supplies" : "shop",
  "agricultural technology" : "company",
  "airfield" : "airport",
  "airline" : "company",
  "airline access" : "access gateway",
  "algerian" : "restaurant",
  "ambulance unit" : "health care service",
  "american" : "restaurant",
  "amphitheater" : "theater",
  "amusement arcade" : "amusement park",
  "amusement place" : "amusement park",
  "animal services" : "shop",
  "animal shelter" : "company",
  "antique/art" : "shop",
  "apartment" : "holiday rental",
  "aquatic zoo marine park" : "zoos, arboreta botanical garden",
  "arabian" : "restaurant",
  "arboreta botanical gardens" : "zoos, arboreta botanical garden",
  "arch" : "important tourist attraction",
  "argentinean" : "restaurant",
  "armenian" : "restaurant",
  "art school" : "school",
  "ashram" : "place of worship",
  "asian (other)" : "restaurant",
  "athletic" : "stadium",
  "atv/snowmobile" : "automotive dealer",
  "australian" : "restaurant",
  "austrian" : "restaurant",
  "automobile" : "company",
  "automobile manufacturing" : "company",
  "bags leatherwear" : "shop",
  "balloonport" : "airport",
  "banquet rooms" : "restaurant",
  "bar" : "nightlife",
  "barbecue" : "restaurant",
  "baseball" : "stadium",
  "basketball" : "stadium",
  "basque" : "restaurant",
  "battlefield" : "park recreation area",
  "bay" : "geographic feature",
  "beach club" : "club association",
  "beauty salon" : "shop",
  "beauty supplies" : "shop",
  "bed breakfast guest houses" : "hotel/motel",
  "belgian" : "restaurant",
  "betting station" : "shop",
  "bistro" : "restaurant",
  "blood bank" : "health care service",
  "boat" : "automotive dealer",
  "boat launching ramp" : "park recreation area",
  "boating equipment accessories" : "shop",
  "bodyshops" : "repair facility",
  "bolivian" : "restaurant",
  "book shops" : "shop",
  "bosnian" : "restaurant",
  "bowling" : "leisure center",
  "brazilian" : "restaurant",
  "bridge" : "important tourist attraction",
  "bridge tunnel operations" : "company",
  "british" : "restaurant",
  "buffet" : "restaurant",
  "building" : "important tourist attraction",
  "bulgarian" : "restaurant",
  "bungalow" : "holiday rental",
  "burmese" : "restaurant",
  "bus" : "automotive dealer",
  "bus charter rentals" : "company",
  "bus lines" : "company",
  "bus stop" : "public transport stop",
  "cabaret" : "theater",
  "cabins lodges" : "hotel/motel",
  "cable telephone" : "company",
  "cafeterias" : "restaurant",
  "cafe" : "café/pub",
  "café" : "café/pub",
  "californian" : "restaurant",
  "cambodian" : "restaurant",
  "canadian" : "restaurant",
  "cape" : "geographic feature",
  "car" : "automotive dealer",
  "car glass replacement shops" : "repair facility",
  "caravan site" : "camping ground",
  "caribbean" : "restaurant",
  "catering" : "company",
  "cave" : "geographic feature",
  "cd's, dvd videos" : "shop",
  "cd/video rental" : "shop",
  "cemetery" : "park recreation area",
  "chalet" : "holiday rental",
  "chemicals" : "company",
  "chicken" : "restaurant",
  "child care facility" : "school",
  "chilean" : "restaurant",
  "chinese" : "restaurant",
  "christmas/holiday store" : "shop",
  "church" : "place of worship",
  "cleaning services" : "company",
  "closed" : "airport",
  "clothing accessories: children" : "shop",
  "clothing accessories: footwear shoe repairs" : "shop",
  "clothing accessories: general" : "shop",
  "clothing accessories: men" : "shop",
  "clothing accessories: specialty" : "shop",
  "clothing accessories: women" : "shop",
  "coach stop" : "public transport stop",
  "cocktail bar" : "nightlife",
  "coffee shop" : "café/pub",
  "colombian" : "restaurant",
  "comedy club" : "nightlife",
  "computer data services" : "company",
  "computer software" : "company",
  "concert hall" : "theater",
  "condominium complex" : "residential accommodation",
  "construction" : "company",
  "construction material equipment" : "shop",
  "convenience stores" : "shop",
  "corsican" : "restaurant",
  "cottage" : "holiday rental",
  "cove" : "geographic feature",
  "creole-cajun" : "restaurant",
  "cricket ground" : "stadium",
  "crêperie" : "restaurant",
  "cuban" : "restaurant",
  "culinary school" : "school",
  "currency exchange" : "exchange",
  "cypriot" : "restaurant",
  "czech" : "restaurant",
  "dance studio school" : "leisure center",
  "danish" : "restaurant",
  "delicatessen" : "shop",
  "dinner theater" : "theater",
  "discotheque" : "nightlife",
  "diversified finanacials" : "company",
  "dominican" : "restaurant",
  "dongbei" : "restaurant",
  "doughnuts" : "restaurant",
  "drive through bottle shop" : "shop",
  "drive-in cinema" : "cinema",
  "driving school" : "school",
  "drug store" : "shop",
  "dry cleaners" : "shop",
  "dune" : "geographic feature",
  "dutch" : "restaurant",
  "egyptian" : "restaurant",
  "electrical appliance" : "shop",
  "electrical, office it: camera's photography" : "shop",
  "electrical, office it: computer computer supplies" : "shop",
  "electrical, office it: consumer electronics" : "shop",
  "electrical, office it: office equipment" : "shop",
  "electronics" : "company",
  "english" : "restaurant",
  "equipment rental" : "company",
  "erotic" : "restaurant",
  "ethiopian" : "restaurant",
  "exotic" : "restaurant",
  "factory outlet" : "shop",
  "fairground" : "park recreation area",
  "farmers" : "market",
  "fast food" : "restaurant",
  "filipino" : "restaurant",
  "finnish" : "restaurant",
  "fishing hunting area" : "park recreation area",
  "fitness club center" : "sports center",
  "flats/apartment complex" : "residential accommodation",
  "florists" : "shop",
  "flying club" : "leisure center",
  "fondue" : "restaurant",
  "food drinks: bakers" : "shop",
  "food drinks: butchers" : "shop",
  "food drinks: fishmongers" : "shop",
  "food drinks: food markets" : "shop",
  "food drinks: food shops" : "shop",
  "food drinks: green grocers" : "shop",
  "food drinks: grocers" : "shop",
  "food drinks: wine spirits" : "shop",
  "football" : "stadium",
  "forest area" : "park recreation area",
  "french" : "restaurant",
  "funeral service mortuaries" : "company",
  "furniture/home furnishings" : "shop",
  "fusion" : "restaurant",
  "general" : "hospital/polyclinic",
  "general car repair servicing" : "repair facility",
  "general practitioner" : "doctor",
  "german" : "restaurant",
  "gifts, cards, novelties souvenirs" : "shop",
  "glassware/ceramic" : "shop",
  "gold exchange" : "exchange",
  "greek" : "restaurant",
  "grill" : "restaurant",
  "guangdong" : "restaurant",
  "gurudwara" : "place of worship",
  "hairdressers barbers" : "shop",
  "hamburgers" : "restaurant",
  "harbor" : "geographic feature",
  "hardware" : "shop",
  "hawaiian" : "restaurant",
  "heliport" : "airport",
  "high school" : "school",
  "hiking" : "trail system",
  "historic site" : "park recreation area",
  "historical park" : "park recreation area",
  "hobby/free time" : "shop",
  "hockey club" : "club association",
  "home appliance repair" : "company",
  "horse racing" : "stadium",
  "horse riding" : "trail system",
  "horticulture" : "agriculture",
  "hospital for women children" : "hospital/polyclinic",
  "hospital of chinese medicine" : "hospital/polyclinic",
  "hostel" : "hotel/motel",
  "hot pot" : "restaurant",
  "hotel" : "hotel/motel",
  "house garden: carpet/floor coverings" : "shop",
  "house garden: curtains/textiles" : "shop",
  "house garden: do-it-yourself centers" : "shop",
  "house garden: furniture fittings" : "shop",
  "house garden: garden centers services" : "shop",
  "house garden: glass windows" : "shop",
  "house garden: kitchens bathrooms" : "shop",
  "house garden: lighting" : "shop",
  "house garden: painting decorating" : "shop",
  "hunan" : "restaurant",
  "hungarian" : "restaurant",
  "ice cream parlor" : "restaurant",
  "ice hockey" : "stadium",
  "import/export distribution" : "company",
  "indian" : "restaurant",
  "indonesian" : "restaurant",
  "informal" : "market",
  "insurance" : "company",
  "international" : "restaurant",
  "internet café" : "café/pub",
  "internet cafe" : "café/pub",
  "investment advisors" : "company",
  "iranian" : "restaurant",
  "irish" : "restaurant",
  "israeli" : "restaurant",
  "italian" : "restaurant",
  "jamaican" : "restaurant",
  "japanese" : "restaurant",
  "jazz club" : "nightlife",
  "jewelry, clocks watches" : "shop",
  "jewish" : "restaurant",
  "junior college/community college" : "college/university",
  "karaoke club" : "nightlife",
  "korean" : "restaurant",
  "kosher" : "restaurant",
  "lagoon" : "geographic feature",
  "lakeshore" : "park recreation area",
  "language school" : "school",
  "large_airport" : "airport",
  "latin american" : "restaurant",
  "laundry" : "shop",
  "lebanese" : "restaurant",
  "legal services" : "company",
  "local" : "post office",
  "local specialities" : "shop",
  "locale" : "geographic feature",
  "lottery shop" : "shop",
  "luxembourgian" : "restaurant",
  "macrobiotic" : "restaurant",
  "maghrib" : "restaurant",
  "mail/package/freight delivery" : "company",
  "maltese" : "restaurant",
  "manufacturing" : "company",
  "marine electronic equipment" : "shop",
  "marsh/swamp/vlei" : "geographic feature",
  "mauritian" : "restaurant",
  "mausoleum/grave" : "important tourist attraction",
  "mechanical engineering" : "company",
  "medical supplies equipment" : "shop",
  "mediterranean" : "restaurant",
  "medium_airport" : "airport",
  "memorial" : "park recreation area",
  "metro" : "railway station",
  "mexican" : "restaurant",
  "microbrewery/beer garden" : "café/pub",
  "middle eastern" : "restaurant",
  "middle school" : "school",
  "military authority" : "airport",
  "mineral/hot springs" : "geographic feature",
  "mining" : "company",
  "mobile phone shop" : "shop",
  "mongolian" : "restaurant",
  "monument" : "important tourist attraction",
  "moroccan" : "restaurant",
  "mosque" : "place of worship",
  "motel" : "hotel/motel",
  "motor sport" : "stadium",
  "motorcycle" : "automotive dealer",
  "motorcycle repair" : "repair facility",
  "mountain bike" : "trail system",
  "mountain peak" : "geographic feature",
  "moving storage" : "company",
  "multi-purpose" : "stadium",
  "music center" : "theater",
  "musical instruments" : "shop",
  "mussels" : "restaurant",
  "nail salon" : "shop",
  "national" : "railway station",
  "natural attraction" : "important tourist attraction",
  "neighbourhood" : "city center",
  "nepalese" : "restaurant",
  "netball" : "stadium",
  "newsagents tobacconists" : "shop",
  "norwegian" : "restaurant",
  "oasis" : "geographic feature",
  "observatory" : "important tourist attraction",
  "oem" : "company",
  "oil natural gas" : "company",
  "opera" : "theater",
  "opticians" : "shop",
  "order 1 area" : "police station",
  "order 2 area" : "government office",
  "order 3 area" : "government office",
  "order 4 area" : "government office",
  "order 5 area" : "government office",
  "order 6 area" : "government office",
  "order 7 area" : "government office",
  "order 8 area" : "government office",
  "order 9 area" : "government office",
  "organic" : "restaurant",
  "oriental" : "restaurant",
  "pakistani" : "restaurant",
  "pan" : "geographic feature",
  "parkway" : "park recreation area",
  "passenger transport ticket office" : "public amenity",
  "pawn shop" : "shop",
  "pedestrian subway" : "public amenity",
  "personal care facility" : "health care service",
  "personal service" : "health care service",
  "peruvian" : "restaurant",
  "pet supplies" : "shop",
  "pharmaceuticals" : "company",
  "photo lab/development" : "shop",
  "photocopy" : "shop",
  "picnic area" : "park recreation area",
  "pizza" : "restaurant",
  "plain/flat" : "geographic feature",
  "planetarium" : "important tourist attraction",
  "plateau" : "geographic feature",
  "polish" : "restaurant",
  "polynesian" : "restaurant",
  "portuguese" : "restaurant",
  "pre school" : "school",
  "preserve" : "park recreation area",
  "primary producer" : "agriculture",
  "primary school" : "school",
  "private authority" : "airport",
  "private club" : "nightlife",
  "provençal" : "restaurant",
  "pub" : "café/pub",
  "pub food" : "restaurant",
  "public" : "market",
  "public authority" : "airport",
  "public call box" : "public amenity",
  "public health technologies" : "company",
  "publishing technologies" : "company",
  "quarry" : "geographic feature",
  "race track" : "stadium",
  "railway siding" : "railway station",
  "rapids" : "geographic feature",
  "real estate" : "company",
  "real estate agents" : "shop",
  "recreation area" : "park recreation area",
  "recreational" : "camping ground",
  "recreational vehicles" : "automotive dealer",
  "recycling shop" : "shop",
  "reef" : "geographic feature",
  "repair shops" : "repair facility",
  "reservoir" : "geographic feature",
  "residential estate" : "residential accommodation",
  "resort" : "hotel/motel",
  "rest camps" : "hotel/motel",
  "retail outlet" : "shop",
  "retirement community" : "residential accommodation",
  "ridge" : "geographic feature",
  "river crossing" : "geographic feature",
  "river scenic area" : "park recreation area",
  "road rescue" : "public amenity",
  "roadside" : "restaurant",
  "rock climbing" : "trail system",
  "rocks" : "geographic feature",
  "rugby ground" : "stadium",
  "rumanian" : "restaurant",
  "russian" : "restaurant",
  "salad bar" : "restaurant",
  "sale installation of car accessories" : "repair facility",
  "sandwich" : "restaurant",
  "sauna, solarium massage" : "leisure center",
  "savings institution" : "company",
  "savoyan" : "restaurant",
  "scandinavian" : "restaurant",
  "scottish" : "restaurant",
  "seafood" : "restaurant",
  "seaplane_base" : "airport",
  "seashore" : "park recreation area",
  "security gate" : "access gateway",
  "security products" : "shop",
  "senior high school" : "school",
  "service" : "company",
  "services" : "company",
  "shandong" : "restaurant",
  "shanghai" : "restaurant",
  "sichuan" : "restaurant",
  "sicilian" : "restaurant",
  "ski resort" : "park recreation area",
  "slavic" : "restaurant",
  "slovak" : "restaurant",
  "small_airport" : "airport",
  "snacks" : "restaurant",
  "snooker, pool billiard" : "leisure center",
  "soccer" : "stadium",
  "soul food" : "restaurant",
  "soup" : "restaurant",
  "spanish" : "restaurant",
  "special" : "hospital/polyclinic",
  "special school" : "school",
  "specialist" : "doctor",
  "specialty foods" : "shop",
  "sport school" : "school",
  "sports equipment clothing" : "shop",
  "squash court" : "sports center",
  "stamp shop" : "shop",
  "station access" : "access gateway",
  "statue" : "important tourist attraction",
  "steak house" : "restaurant",
  "stock exchange" : "exchange",
  "sudanese" : "restaurant",
  "supermarkets hypermarkets" : "market",
  "supra national" : "government office",
  "surinamese" : "restaurant",
  "sushi" : "restaurant",
  "swedish" : "restaurant",
  "swiss" : "restaurant",
  "synagogue" : "place of worship",
  "syrian" : "restaurant",
  "tailor shop" : "shop",
  "taiwanese" : "restaurant",
  "take away" : "restaurant",
  "tapas" : "restaurant",
  "tax services" : "company",
  "taxi stand" : "public transport stop",
  "taxi, limousine shuttle service" : "company",
  "tea house" : "café/pub",
  "tele communications" : "company",
  "temple" : "place of worship",
  "teppanyakki" : "restaurant",
  "thai" : "restaurant",
  "thematic sport" : "sports center",
  "tibetan" : "restaurant",
  "toilet" : "public amenity",
  "tower" : "important tourist attraction",
  "townhouse complex" : "residential accommodation",
  "toys games" : "shop",
  "traffic control department" : "traffic service center",
  "tram stop" : "public transport stop",
  "transport" : "company",
  "travel agents" : "shop",
  "truck" : "automotive dealer",
  "truck repair service" : "repair facility",
  "tunisian" : "restaurant",
  "tunnel" : "important tourist attraction",
  "turkish" : "restaurant",
  "tyre (tire) services" : "repair facility",
  "uruguayan" : "restaurant",
  "valley" : "geographic feature",
  "van" : "automotive dealer",
  "variety store" : "shop",
  "vegetarian" : "restaurant",
  "venezuelan" : "restaurant",
  "vietnamese" : "restaurant",
  "villa" : "holiday rental",
  "vocational training" : "school",
  "water hole" : "important tourist attraction",
  "wedding services" : "company",
  "weigh scales" : "weigh station",
  "well" : "geographic feature",
  "welsh" : "restaurant",
  "western continental" : "restaurant",
  "wholesale clubs" : "shop",
  "wilderness area" : "park recreation area",
  "wildlife park" : "zoos, arboreta botanical garden",
  "wine bar" : "nightlife",
  "winter sport" : "park recreation area",
  "yacht basin" : "marina",
  "yogurt/juice bar" : "restaurant",
  "zoo" : "zoos, arboreta botanical garden"
}